---
id: debian-certbot
base_name: certbot
tags:
- debian
- letsencrypt
- certbot
presentation_date: '2016-12-10'
version: 2016.12.10
licenses: []
slideshare_id: certbottls
speaker_deck_id: certbotdewu-liao-tlssaba
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
